# Generated by Django 6.0.6 on 2026-06-25 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSeeker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CAREER', 'Career'), ('RESEARCH', 'Research'), ('TECH', 'Tech'), ('EDUCATION', 'Education'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('PHYSICS', 'Physics'), ('ASTRONOMY', 'Astronomy'), ('LITERATURE', 'Literature'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('CONNECTED', 'Connected'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('learning_goal', models.TextField(blank=True)),
                ('interest', models.CharField(choices=[('CAREER', 'Career'), ('RESEARCH', 'Research'), ('TECH', 'Tech'), ('EDUCATION', 'Education'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('PHYSICS', 'Physics'), ('ASTRONOMY', 'Astronomy'), ('LITERATURE', 'Literature'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='TECH', max_length=30)),
                ('custom_interest', models.CharField(blank=True, max_length=100)),
                ('is_rural', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
