# Generated by Django 6.0.6 on 2026-06-28 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_answerseeker_seekerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('expertise', models.CharField(choices=[('CAREER', 'Career'), ('RESEARCH', 'Research'), ('TECH', 'Tech'), ('EDUCATION', 'Education'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('PHYSICS', 'Physics'), ('ASTRONOMY', 'Astronomy'), ('LITERATURE', 'Literature'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='TECH', max_length=30)),
                ('custom_expertise', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('badge_level', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply', models.TextField()),
                ('share_contact', models.BooleanField(default=False)),
                ('contact_info', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.answerseeker')),
            ],
        ),
    ]
