# Generated by Django 6.0.6 on 2026-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mentorprofile_mentorreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='interest',
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='interests',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.JSONField(default=list),
        ),
    ]
