# Generated by Django 6.0.6 on 2026-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_seekerprofile_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerseeker',
            name='ai_category',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='answerseeker',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
