# Generated by Django 6.0.6 on 2026-07-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_answerseeker_ai_category_answerseeker_ai_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerseeker',
            name='ai_category',
        ),
        migrations.AddField(
            model_name='answerseeker',
            name='ai_categories',
            field=models.JSONField(default=list),
        ),
    ]
