# Generated by Django 6.0.6 on 2026-07-20 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_answerseeker_ai_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerseeker',
            name='selected_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
